"""
Export the trained XGBoost classifier to pure JavaScript (no onnxruntime).
Used by NestJS on Vercel where native ONNX binaries exceed the 250 MB limit.
"""
from __future__ import annotations

import json
from pathlib import Path

import joblib
import m2cgen as m

ROOT = Path(__file__).resolve().parent
JOBLIB_PATH = ROOT / "models" / "attrition_v1.joblib"
SCHEMA_PATH = ROOT / "models" / "feature_schema.json"
OUT_JS = ROOT.parent / "src" / "ml" / "generated" / "classifier.js"
OUT_META = ROOT.parent / "src" / "ml" / "generated" / "classifier.meta.json"


def export() -> None:
    pipeline = joblib.load(JOBLIB_PATH)
    classifier = pipeline.named_steps["classifier"]
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))

    js_code = m.export_to_javascript(
        classifier,
        function_name="scoreAttritionLeaves",
    )

    OUT_JS.parent.mkdir(parents=True, exist_ok=True)
    wrapper = f"""// Auto-generated by data.mining/export_xgboost_js.py — do not edit manually.
{js_code}

function sigmoid(x) {{
  if (x >= 0) {{
    const z = Math.exp(-x);
    return 1 / (1 + z);
  }}
  const z = Math.exp(x);
  return z / (1 + z);
}}

/**
 * @param {{number[]}} features Preprocessed feature vector (length {schema.get('transformedFeatureCount', 67)})
 * @returns {{ probability: number, predictedAttrition: boolean }}
 */
function predictAttritionFromVector(features) {{
  const margin = scoreAttritionLeaves(features);
  const probability = sigmoid(margin);
  return {{
    probability,
    predictedAttrition: probability >= 0.5,
  }};
}}

module.exports = {{ scoreAttritionLeaves, predictAttritionFromVector }};
"""
    OUT_JS.write_text(wrapper, encoding="utf-8")

    meta = {
        "modelVersion": schema.get("modelVersion", "attrition-xgb-v1"),
        "transformedFeatureCount": schema.get("transformedFeatureCount"),
        "exportMethod": "m2cgen-javascript",
    }
    OUT_META.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    print(f"Exported JS classifier: {OUT_JS}")
    print(f"File size KB: {OUT_JS.stat().st_size / 1024:.1f}")


if __name__ == "__main__":
    export()
